# Generated by Django 5.0.2 on 2024-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
